"""
build_synonyms.py — one-off generator for synonyms.csv

Produces a curated concept -> related-terms dictionary used by the Category
Recommendation tab for query expansion. Each concept carries 50-60 related
terms: English synonyms, sub-types, common spelling variations, and
Hinglish / Hindi transliterations (as buyers actually type them).

CSV columns:
    concept       — canonical, human-readable label for the concept
    category_hint — GeM-style words most likely to appear in matching category
                    names (helps ground the expansion)
    terms         — ';'-separated related terms (deduped, lowercased)
"""
import csv, os

# concept: (category_hint, [terms...])
CONCEPTS = {
    "Mobile Phone / Smartphone": ("mobile phone smartphone cellular", [
        "mobile", "mobile phone", "mobiles", "smartphone", "smart phone", "smartphones",
        "phone", "phones", "cellphone", "cell phone", "cellular phone", "handset",
        "handsets", "android phone", "ios phone", "iphone", "feature phone",
        "keypad phone", "touchscreen phone", "5g phone", "4g phone", "dual sim phone",
        "basic phone", "camera phone", "gsm phone", "rugged phone", "foldable phone",
        "mobile handset", "mobile device", "cell", "smart mobile", "mobile set",
        "phone set", "smart fone", "fone", "mobail", "mobile fone", "mobayl",
        "smartfone", "cellfone", "phone device", "pocket phone", "sim phone",
        "gsm handset", "budget smartphone", "flagship phone", "mobile telephone",
        "wireless phone", "cordless phone", "handheld phone", "communication device",
        "mobile unit", "portable phone", "smart handset",
    ]),
    "Laptop / Notebook Computer": ("laptop notebook computer", [
        "laptop", "laptops", "notebook", "notebooks", "notebook computer",
        "laptop computer", "portable computer", "ultrabook", "ultrabooks",
        "macbook", "chromebook", "netbook", "gaming laptop", "business laptop",
        "thin laptop", "slim laptop", "2 in 1 laptop", "convertible laptop",
        "touchscreen laptop", "laptop pc", "notebook pc", "lap top", "labtop",
        "laptap", "lap-top", "portable pc", "workstation laptop", "student laptop",
        "office laptop", "personal laptop", "i3 laptop", "i5 laptop", "i7 laptop",
        "core i5 laptop", "ryzen laptop", "windows laptop", "laptop machine",
        "computer laptop", "notebook machine", "mini laptop", "compact laptop",
        "lightweight laptop", "professional laptop", "commercial laptop",
        "corporate laptop", "portable notebook", "notebook device", "laptop device",
        "laptop system", "mobile computer", "clamshell laptop", "premium laptop",
        "entry level laptop", "budget laptop", "high end laptop",
    ]),
    "Desktop Computer / PC": ("desktop computer personal", [
        "desktop", "desktops", "desktop computer", "desktop pc", "pc", "personal computer",
        "computer", "computers", "cpu", "tower pc", "tower computer", "all in one pc",
        "all-in-one computer", "aio pc", "workstation", "workstations", "computer set",
        "computer system", "branded desktop", "assembled desktop", "gaming pc",
        "office computer", "office pc", "desktop machine", "desktop system",
        "computr", "compter", "kampyuter", "computer machine", "desktop unit",
        "mini pc", "small form factor pc", "sff pc", "thin client", "i5 desktop",
        "i7 desktop", "core i5 desktop", "windows pc", "business pc", "commercial pc",
        "corporate desktop", "student desktop", "home computer", "cpu cabinet",
        "computer tower", "processor unit", "desktop processor", "complete pc",
        "full computer set", "computer with monitor", "pc system", "computing device",
        "workhorse pc", "entry level desktop", "high end desktop", "branded pc",
    ]),
    "Printer / Multifunction": ("printer multifunction scanner", [
        "printer", "printers", "printing machine", "laser printer", "inkjet printer",
        "inkjet", "laserjet", "dot matrix printer", "multifunction printer", "mfp",
        "all in one printer", "all-in-one printer", "photocopier", "copier",
        "xerox machine", "xerox", "scanner cum printer", "print machine",
        "color printer", "colour printer", "monochrome printer", "black and white printer",
        "wireless printer", "wifi printer", "network printer", "thermal printer",
        "barcode printer", "label printer", "photo printer", "office printer",
        "printr", "priter", "printar", "printing device", "print device",
        "duplex printer", "a4 printer", "a3 printer", "duplicator", "ink tank printer",
        "cartridge printer", "toner printer", "3d printer", "receipt printer",
        "passbook printer", "id card printer", "portable printer", "compact printer",
        "high speed printer", "heavy duty printer", "document printer",
        "multifunction device", "copy machine", "printing solution",
    ]),
    "Spectacles / Eyewear": ("spectacles eyewear goggles", [
        "chashma", "chasma", "chashmaa", "chashma", "spectacle", "spectacles",
        "glasses", "eye glasses", "eyeglasses", "eyewear", "eye wear", "goggles",
        "goggle", "sunglasses", "sun glasses", "reading glasses", "optical glasses",
        "prescription glasses", "power glasses", "safety glasses", "protective glasses",
        "safety goggles", "protective goggles", "lab goggles", "swimming goggles",
        "shades", "specs", "nazar ka chashma", "aankh ka chashma", "chashme",
        "chashmey", "ainak", "ainaka", "eye protection", "vision glasses",
        "bifocal glasses", "progressive glasses", "anti glare glasses", "computer glasses",
        "spectacle frame", "optical frame", "eyeglass frame", "frame and lens",
        "corrective eyewear", "vision correction glasses", "welding goggles",
        "industrial goggles", "dust goggles", "riding goggles", "safety spectacles",
        "clear glasses", "tinted glasses", "photochromic glasses", "spec",
        "eyesight glasses", "optical eyewear", "protective eyewear",
    ]),
    "Chair / Seating": ("chair seating furniture", [
        "chair", "chairs", "kursi", "kursiyan", "kurси", "seat", "seating",
        "office chair", "revolving chair", "executive chair", "visitor chair",
        "conference chair", "ergonomic chair", "study chair", "computer chair",
        "gaming chair", "folding chair", "plastic chair", "steel chair",
        "wooden chair", "mesh chair", "high back chair", "mid back chair",
        "low back chair", "arm chair", "armchair", "recliner", "recliner chair",
        "waiting chair", "bench chair", "stool", "bar stool", "swivel chair",
        "task chair", "boss chair", "staff chair", "student chair", "cushion chair",
        "leather chair", "chair set", "seating chair", "office seating",
        "revolving seat", "sofa chair", "director chair", "chairman chair",
        "pushback chair", "auditorium chair", "canteen chair", "class room chair",
        "molded chair", "moulded chair", "banquet chair", "reception chair",
        "chaire", "chiar",
    ]),
    "Table / Desk": ("table desk furniture", [
        "table", "tables", "mez", "mej", "table desk", "desk", "desks",
        "office table", "office desk", "computer table", "study table", "writing table",
        "workstation table", "conference table", "meeting table", "dining table",
        "center table", "centre table", "side table", "corner table", "reception table",
        "executive table", "officer table", "staff table", "folding table",
        "plastic table", "steel table", "wooden table", "modular table",
        "workstation desk", "computer desk", "writing desk", "office workstation",
        "laptop table", "portable table", "adjustable table", "height adjustable table",
        "standing desk", "student table", "class room table", "canteen table",
        "meej", "tabel", "tebal", "work table", "utility table", "display table",
        "counter table", "cabin table", "boardroom table", "training table",
        "lab table", "workbench", "work bench", "instrument table",
    ]),
    "Air Conditioner (AC)": ("air conditioner conditioning", [
        "ac", "a.c.", "air conditioner", "air conditioners", "air conditioning",
        "airconditioner", "air-conditioner", "split ac", "window ac", "cassette ac",
        "tower ac", "portable ac", "central ac", "vrf ac", "vrv ac", "ductable ac",
        "inverter ac", "1 ton ac", "1.5 ton ac", "2 ton ac", "split air conditioner",
        "window air conditioner", "wall mounted ac", "floor standing ac",
        "cooling machine", "cooling unit", "ac unit", "ac machine", "hvac",
        "ac system", "air cooler ac", "climate control", "room ac", "office ac",
        "ac 1.5 ton", "star rated ac", "5 star ac", "3 star ac", "energy efficient ac",
        "cooling ac", "air condition", "airconditioning", "ac indoor unit",
        "ac outdoor unit", "split unit", "hi wall ac", "commercial ac",
        "cassette air conditioner", "precision ac", "server room ac", "ac cooling",
        "conditioner", "refrigeration ac", "chilled ac", "ac appliance",
    ]),
    "Refrigerator / Fridge": ("refrigerator freezer cooling", [
        "fridge", "refrigerator", "refrigerators", "frij", "freeze", "friz",
        "refrigrator", "refridgerator", "double door fridge", "single door fridge",
        "triple door fridge", "side by side fridge", "mini fridge", "bar fridge",
        "deep freezer", "chest freezer", "upright freezer", "visi cooler",
        "visicooler", "water cooler cum refrigerator", "cold storage",
        "commercial refrigerator", "domestic refrigerator", "frost free fridge",
        "direct cool fridge", "inverter refrigerator", "convertible fridge",
        "refrigerator freezer", "fridge freezer", "cooling appliance", "cold box",
        "medical refrigerator", "vaccine refrigerator", "laboratory refrigerator",
        "blood bank refrigerator", "pharmacy refrigerator", "ice lined refrigerator",
        "ilr", "freezer box", "cooler fridge", "5 star refrigerator",
        "3 star refrigerator", "300 litre fridge", "double-door refrigerator",
        "refrigeration unit", "chiller", "cooling cabinet", "food refrigerator",
        "kitchen fridge", "office fridge", "godrej fridge", "fridge appliance",
        "cold cabinet", "refrigerating machine", "freezing unit",
    ]),
    "Fan / Ventilation": ("fan ventilation cooling", [
        "fan", "fans", "pankha", "pankha", "ceiling fan", "table fan", "pedestal fan",
        "wall fan", "exhaust fan", "stand fan", "tower fan", "bldc fan",
        "cooler fan", "industrial fan", "cabin fan", "mini fan", "usb fan",
        "rechargeable fan", "high speed fan", "energy saving fan", "decorative fan",
        "electric fan", "cooling fan", "air circulator", "ventilation fan",
        "wall mounted fan", "bracket fan", "farrata fan", "pankhe", "panka",
        "fann", "faan", "blower fan", "portable fan", "remote fan",
        "5 star fan", "bldc ceiling fan", "sweep fan", "1200 mm fan", "600 mm fan",
        "office fan", "class room fan", "school fan", "ventilator fan",
        "chimney exhaust fan", "kitchen exhaust fan", "air blower", "circulation fan",
        "ac fan", "dc fan", "silent fan", "designer fan", "hvls fan",
        "heavy duty fan", "wall bracket fan",
    ]),
    "LED Bulb / Lighting": ("led light lamp luminaire", [
        "bulb", "bulbs", "led bulb", "led bulbs", "light", "lights", "batti", "batati",
        "lamp", "lamps", "led light", "led lights", "tube light", "tubelight",
        "led tube", "led tubelight", "cfl", "cfl bulb", "led panel", "panel light",
        "flood light", "floodlight", "street light", "streetlight", "led street light",
        "down light", "downlight", "spot light", "spotlight", "ceiling light",
        "led lamp", "night lamp", "study lamp", "table lamp", "emergency light",
        "led flood light", "high mast light", "solar light", "solar street light",
        "batti led", "led batti", "bulp", "buld", "light bulb", "luminaire",
        "led luminaire", "led fitting", "light fitting", "led fixture",
        "batten light", "led batten", "cob light", "gate light", "focus light",
        "led downlighter", "concealed light", "rope light", "decorative light",
        "9 watt led", "led 9w", "energy saving bulb", "smart bulb", "indoor light",
        "outdoor light",
    ]),
    "UPS / Inverter / Battery": ("ups inverter battery power backup", [
        "ups", "u.p.s.", "inverter", "inverters", "battery", "batteries", "battry",
        "batery", "power backup", "backup power", "online ups", "offline ups",
        "line interactive ups", "1 kva ups", "2 kva ups", "5 kva ups", "10 kva ups",
        "home inverter", "solar inverter", "inverter battery", "tubular battery",
        "smf battery", "vrla battery", "sealed battery", "lead acid battery",
        "lithium battery", "li-ion battery", "ups battery", "power inverter",
        "sine wave inverter", "pure sine wave inverter", "invertor", "inverter ups",
        "battery backup", "backup battery", "battery bank", "power storage",
        "energy storage", "solar battery", "gel battery", "deep cycle battery",
        "battery charger inverter", "ups system", "uninterruptible power supply",
        "power supply unit", "standby power", "emergency power", "invrter",
        "battery cell", "storage battery", "12v battery", "150 ah battery",
        "online ups 1 kva", "rack mount ups", "server ups", "battary",
    ]),
    "CCTV / Surveillance Camera": ("cctv surveillance camera security", [
        "cctv", "cc tv", "cctv camera", "surveillance camera", "security camera",
        "camera cctv", "ip camera", "dome camera", "bullet camera", "ptz camera",
        "wireless camera", "wifi camera", "night vision camera", "hd camera",
        "4k camera", "spy camera", "hidden camera", "outdoor camera", "indoor camera",
        "dvr", "nvr", "cctv dvr", "cctv nvr", "video surveillance", "monitoring camera",
        "cctv system", "cctv setup", "security cctv", "surveillance system",
        "cctv installation", "analog camera", "hikvision camera", "cp plus camera",
        "cctv kit", "camera security", "seesee tv", "cc camera", "cctv camra",
        "survelance camera", "surveilance camera", "recording camera",
        "office cctv", "shop cctv", "home cctv", "boundary camera", "gate camera",
        "vari focal camera", "fixed camera", "poe camera", "thermal camera",
        "cctv recorder", "network video recorder", "digital video recorder",
        "cameras", "security surveillance",
    ]),
    "Projector / Display": ("projector display screen", [
        "projector", "projectors", "lcd projector", "dlp projector", "led projector",
        "laser projector", "digital projector", "portable projector", "mini projector",
        "short throw projector", "ultra short throw projector", "classroom projector",
        "conference projector", "office projector", "home theatre projector",
        "projection machine", "projector screen", "projection screen", "screen projector",
        "overhead projector", "ohp", "smart projector", "4k projector", "hd projector",
        "full hd projector", "3000 lumens projector", "high lumens projector",
        "projecter", "projektor", "prijector", "beam projector", "video projector",
        "presentation projector", "interactive projector", "ceiling projector",
        "multimedia projector", "training projector", "auditorium projector",
        "projector with screen", "wall projector", "smart board projector",
        "interactive panel", "display board", "digital display", "led display",
        "video wall", "presentation screen", "motorized screen", "tripod screen",
        "wall mount screen", "projection display", "beamer",
    ]),
    "Water Purifier / RO": ("water purifier ro filter", [
        "water purifier", "ro", "r.o.", "ro system", "ro water purifier",
        "water filter", "purifier", "purifiers", "uv purifier", "uf purifier",
        "ro uv purifier", "ro uv uf purifier", "water purification system",
        "drinking water purifier", "aquaguard", "kent purifier", "water cleaner",
        "water treatment plant", "wtp", "water softener", "commercial ro",
        "domestic ro", "industrial ro", "ro plant", "water purify machine",
        "paani purifier", "pani filter", "water shodhak", "jal shodhan",
        "ro machine", "purifier ro", "reverse osmosis system", "mineral water purifier",
        "alkaline purifier", "gravity water filter", "under sink ro", "wall mounted ro",
        "water dispenser purifier", "purifier machine", "water filtration",
        "filter machine", "watr purifier", "watter purifier", "ro filter",
        "membrane filter", "sediment filter", "drinking water system",
        "public water purifier", "school water purifier", "office water purifier",
        "hand pump purifier", "ro cartridge system", "tds purifier",
    ]),
    "Stationery (Pen / Paper)": ("stationery paper writing office", [
        "stationery", "stationary", "pen", "pens", "kalam", "kalm", "ballpoint pen",
        "ball pen", "gel pen", "marker", "markers", "sketch pen", "pencil", "pencils",
        "paper", "papers", "a4 paper", "a4 sheet", "copier paper", "printing paper",
        "notebook", "notebooks", "register", "registers", "file", "files", "folder",
        "folders", "envelope", "envelopes", "stapler", "staplers", "stapler pin",
        "punching machine", "paper clip", "clips", "rubber band", "eraser", "sharpener",
        "highlighter", "whiteboard marker", "permanent marker", "office stationery",
        "school stationery", "writing pad", "note pad", "notepad", "sticky notes",
        "post it", "glue", "gum", "scissor", "scissors", "tape", "cello tape",
        "calculator", "office supplies", "writing material", "paper sheet",
        "photocopy paper", "bond paper", "letter head", "kagaz", "kaagaz", "copy",
    ]),
    "Shoes / Footwear": ("footwear shoes safety", [
        "shoe", "shoes", "joota", "joote", "jute", "footwear", "foot wear",
        "safety shoes", "safety shoe", "industrial shoes", "steel toe shoes",
        "sports shoes", "running shoes", "sneakers", "canvas shoes", "leather shoes",
        "formal shoes", "casual shoes", "office shoes", "school shoes", "boots",
        "gum boots", "gumboot", "rubber boots", "rain boots", "army boots",
        "combat boots", "ankle boots", "sandal", "sandals", "slipper", "slippers",
        "chappal", "chappals", "floaters", "loafers", "juta", "jhoota", "shoos",
        "footwears", "boot", "work boots", "trekking shoes", "hiking shoes",
        "pvc shoes", "moulded shoes", "safety footwear", "protective footwear",
        "labour shoes", "worker shoes", "uniform shoes", "black shoes",
        "electrical safety shoes", "anti skid shoes",
    ]),
    "Uniform / Clothing": ("uniform apparel clothing garment", [
        "uniform", "uniforms", "vardi", "wardi", "kapda", "kapde", "clothing",
        "apparel", "garment", "garments", "dress", "dresses", "shirt", "shirts",
        "t shirt", "tshirt", "t-shirt", "trouser", "trousers", "pant", "pants",
        "school uniform", "office uniform", "staff uniform", "security uniform",
        "guard uniform", "police uniform", "army uniform", "hospital uniform",
        "nurse uniform", "housekeeping uniform", "worker uniform", "labour uniform",
        "coverall", "boiler suit", "overall", "jacket", "jackets", "blazer",
        "coat", "raincoat", "rain coat", "safety jacket", "reflective jacket",
        "high visibility jacket", "hi vis jacket", "saree", "sari", "kurta",
        "salwar", "cap", "topi", "uniform cloth", "uniform fabric", "readymade uniform",
        "corporate uniform", "sports uniform", "track suit", "tracksuit", "sweater",
        "woolen uniform", "summer uniform", "winter uniform", "uniform set",
    ]),
    "Medicine / Pharmaceutical": ("medicine drug pharmaceutical tablet", [
        "medicine", "medicines", "dawa", "dawai", "dava", "davai", "drug", "drugs",
        "pharmaceutical", "pharmaceuticals", "tablet", "tablets", "capsule", "capsules",
        "syrup", "syrups", "injection", "injections", "vaccine", "vaccines",
        "ointment", "cream medicine", "medical drug", "generic medicine",
        "antibiotic", "antibiotics", "painkiller", "pain killer", "analgesic",
        "paracetamol", "antacid", "vitamin", "vitamins", "supplement", "supplements",
        "ivfluid", "iv fluid", "saline", "glucose", "oral medicine", "prescription medicine",
        "otc medicine", "life saving drug", "essential medicine", "medicin",
        "medecine", "dwa", "goli", "goliyan", "pharma", "pharma product",
        "medical supplies", "drug formulation", "api drug", "bulk drug",
        "surgical medicine", "hospital medicine", "veterinary medicine",
        "ayurvedic medicine", "homeopathic medicine", "eye drops", "ear drops",
    ]),
    "Vehicle / Car": ("vehicle car motor transport", [
        "vehicle", "vehicles", "car", "cars", "gaadi", "gadi", "gaari", "motor car",
        "motor vehicle", "automobile", "four wheeler", "4 wheeler", "sedan", "hatchback",
        "suv", "muv", "van", "tempo", "jeep", "mini bus", "bus", "buses",
        "truck", "trucks", "lorry", "pickup", "pick up van", "ambulance",
        "ambulence", "staff car", "official car", "government vehicle", "electric car",
        "ev car", "electric vehicle", "petrol car", "diesel car", "cng car",
        "two wheeler", "2 wheeler", "motorcycle", "motor cycle", "bike", "scooter",
        "scooty", "moped", "tractor", "tempo traveller", "school bus", "passenger vehicle",
        "goods vehicle", "commercial vehicle", "transport vehicle", "utility vehicle",
        "car vehicle", "motorcar", "vehical", "vehcile", "gari", "carriage",
        "conveyance", "fleet vehicle",
    ]),
    "Tyre / Tube": ("tyre tube wheel rubber", [
        "tyre", "tyres", "tire", "tires", "tayar", "tayer", "tyer", "tube",
        "tubes", "tyre tube", "car tyre", "truck tyre", "bus tyre", "bike tyre",
        "scooter tyre", "tractor tyre", "two wheeler tyre", "four wheeler tyre",
        "radial tyre", "tubeless tyre", "nylon tyre", "retreaded tyre", "solid tyre",
        "industrial tyre", "forklift tyre", "otr tyre", "off road tyre",
        "rubber tyre", "wheel tyre", "spare tyre", "vehicle tyre", "automobile tyre",
        "mrf tyre", "ceat tyre", "apollo tyre", "jk tyre", "tyre and tube",
        "inner tube", "tire tube", "pneumatic tyre", "trolley tyre", "cycle tyre",
        "bicycle tyre", "heavy vehicle tyre", "lcv tyre", "hcv tyre", "tayre",
        "taier", "tyar", "wheel rubber", "rubber tube", "tractor tube",
        "truck tube", "flap tyre", "tyre flap", "new tyre", "replacement tyre",
    ]),
    "Cement / Construction Material": ("cement construction building material", [
        "cement", "ciment", "siment", "opc cement", "ppc cement", "portland cement",
        "white cement", "grey cement", "43 grade cement", "53 grade cement",
        "construction material", "building material", "concrete", "rmc",
        "ready mix concrete", "sand", "aggregate", "gravel", "brick", "bricks",
        "fly ash brick", "cement block", "concrete block", "aac block",
        "hollow block", "tmt bar", "reinforcement steel", "binding wire",
        "cement bag", "cement bags", "masonry material", "plaster", "mortar",
        "gypsum", "pop plaster", "putty", "wall putty", "tiles adhesive",
        "construction cement", "civil material", "raw material construction",
        "cemnt", "cemant", "cementt", "cement grade", "bulk cement", "bagged cement",
        "acc cement", "ultratech cement", "ambuja cement", "birla cement",
        "building block", "stone aggregate", "coarse aggregate", "fine aggregate",
        "m sand", "river sand", "rebar",
    ]),
    "Steel / Iron": ("steel iron metal structural", [
        "steel", "iron", "loha", "lohaa", "stainless steel", "ss", "ms steel",
        "mild steel", "steel plate", "iron plate", "steel sheet", "ms sheet",
        "gi sheet", "galvanized sheet", "steel rod", "iron rod", "tmt bar",
        "tmt steel", "reinforcement bar", "rebar", "steel angle", "ms angle",
        "channel steel", "ms channel", "steel beam", "i beam", "h beam",
        "steel pipe", "ms pipe", "gi pipe", "steel section", "structural steel",
        "steel wire", "iron wire", "steel bar", "flat bar", "square bar",
        "round bar", "steel coil", "hr coil", "cr coil", "stil", "steal",
        "steel material", "metal steel", "ferrous metal", "steel scrap",
        "iron scrap", "steel billet", "steel ingot", "steel strip", "steel tube",
        "steel fabrication", "steel structure", "structural iron", "lohe ka",
    ]),
    "Paint / Coating": ("paint coating primer emulsion", [
        "paint", "paints", "rang", "rangai", "colour paint", "color paint",
        "emulsion", "emulsion paint", "distemper", "enamel paint", "enamel",
        "primer", "wall paint", "exterior paint", "interior paint", "acrylic paint",
        "oil paint", "water based paint", "epoxy paint", "epoxy coating",
        "anti corrosive paint", "red oxide", "putty paint", "texture paint",
        "spray paint", "road marking paint", "luminous paint", "wood paint",
        "metal paint", "industrial paint", "protective coating", "coating",
        "varnish", "lacquer", "thinner", "paint thinner", "asian paints",
        "berger paint", "nerolac paint", "rangroghan", "paint colour", "paent",
        "peint", "wall colour", "building paint", "cement paint", "weatherproof paint",
        "waterproof paint", "matt paint", "gloss paint", "satin paint", "undercoat",
        "top coat", "base coat",
    ]),
    "Water Bottle / Flask": ("water bottle flask container", [
        "water bottle", "bottle", "bottles", "botal", "botel", "pani ki botal",
        "steel bottle", "stainless steel bottle", "plastic bottle", "sipper",
        "sipper bottle", "flask", "vacuum flask", "thermos", "thermos flask",
        "insulated bottle", "hot and cold bottle", "sports bottle", "gym bottle",
        "school water bottle", "kids water bottle", "reusable bottle", "copper bottle",
        "glass bottle", "drinking bottle", "water flask", "travel bottle",
        "1 litre bottle", "500 ml bottle", "1 ltr bottle", "water container",
        "pani botal", "watr bottle", "watter bottle", "bottal", "bootle",
        "office water bottle", "leak proof bottle", "bpa free bottle", "tumbler",
        "steel flask", "vaccum flask", "hot water flask", "cold water bottle",
        "beverage bottle", "fridge bottle", "eco bottle", "aluminium bottle",
        "single wall bottle", "double wall bottle", "wide mouth bottle",
        "narrow mouth bottle",
    ]),
    "Fire Extinguisher / Fire Safety": ("fire extinguisher safety fighting", [
        "fire extinguisher", "extinguisher", "fire safety", "fire fighting",
        "fire fighting equipment", "fire cylinder", "co2 extinguisher",
        "abc extinguisher", "dcp extinguisher", "foam extinguisher",
        "water extinguisher", "fire suppression", "fire hose", "fire hydrant",
        "fire alarm", "smoke detector", "fire detector", "fire ball",
        "fire blanket", "fire bucket", "sand bucket", "fire safety equipment",
        "fire protection", "fire suppression system", "sprinkler", "fire sprinkler",
        "fire pump", "hose reel", "fire hose reel", "fire suit", "fireman suit",
        "fire proximity suit", "fire helmet", "fire retardant", "fire resistant",
        "aag bujhane wala", "agnishaman", "fire cylinder refilling",
        "extingusher", "extinguesher", "fire estinguisher", "fire equipment",
        "fire safety system", "portable extinguisher", "trolley extinguisher",
        "clean agent extinguisher", "modular extinguisher", "fire alarm system",
        "fire cabinet", "safety fire equipment", "emergency fire equipment",
        "fire escape",
    ]),
    "Solar Panel / Solar Power": ("solar panel photovoltaic power", [
        "solar panel", "solar panels", "solar", "solar power", "photovoltaic",
        "pv panel", "pv module", "solar module", "solar plate", "solar system",
        "rooftop solar", "roof top solar", "solar power plant", "solar energy system",
        "on grid solar", "off grid solar", "grid tied solar", "hybrid solar",
        "solar inverter", "solar battery", "solar charge controller", "solar street light",
        "solar water heater", "solar pump", "solar water pump", "solar light",
        "solar lantern", "solar home system", "monocrystalline panel",
        "polycrystalline panel", "mono panel", "poly panel", "solar cell",
        "solar kit", "solar power system", "renewable energy system", "green energy",
        "soler panel", "solr panel", "solar pannel", "solar setup", "kwp solar",
        "1 kw solar", "5 kw solar", "solar rooftop plant", "spv panel",
        "solar photovoltaic", "solar generation", "solar power pack",
        "sun power panel", "solar array", "pv system", "solar power supply",
    ]),
    "Television (TV)": ("television tv display led", [
        "tv", "television", "televisions", "led tv", "smart tv", "lcd tv",
        "oled tv", "qled tv", "4k tv", "uhd tv", "full hd tv", "hd tv",
        "android tv", "google tv", "32 inch tv", "43 inch tv", "55 inch tv",
        "65 inch tv", "smart led tv", "digital tv", "flat screen tv", "flat tv",
        "wall mount tv", "colour tv", "color tv", "telivision", "televison",
        "tivi", "tv set", "television set", "display tv", "large screen tv",
        "screen tv", "interactive tv", "signage tv", "commercial tv",
        "office tv", "conference tv", "led television", "smart television",
        "internet tv", "webos tv", "tizen tv", "curved tv", "big screen tv",
        "home tv", "monitor tv", "hdtv", "uhdtv", "wide screen tv", "hd ready tv",
        "budget tv", "premium tv",
    ]),
    "Washing Machine": ("washing machine laundry", [
        "washing machine", "washing machines", "washer", "kapde dhone ki machine",
        "kapda washing machine", "front load washing machine", "top load washing machine",
        "fully automatic washing machine", "semi automatic washing machine",
        "front loading washer", "top loading washer", "laundry machine",
        "clothes washer", "automatic washing machine", "dryer", "clothes dryer",
        "washer dryer", "commercial washing machine", "industrial washing machine",
        "domestic washing machine", "6 kg washing machine", "7 kg washing machine",
        "8 kg washing machine", "inverter washing machine", "washing masin",
        "washing mashine", "washng machine", "wasing machine", "laundry equipment",
        "clothes washing machine", "twin tub washing machine", "single tub washing machine",
        "heavy duty washing machine", "hospital laundry machine", "hostel washing machine",
        "washer machine", "garment washer", "laundry washer", "spin dryer",
        "tumble dryer", "washing appliance", "cloth washer", "washing unit",
        "front load washer", "top load washer", "dhulai machine", "washing solution",
        "kapda dhulai machine", "automatic washer", "clothes washing appliance",
        "domestic washer", "commercial washer", "9 kg washing machine",
    ]),
    "Kitchen Equipment / Utensils": ("kitchen utensil cookware equipment", [
        "utensil", "utensils", "bartan", "bertan", "kitchenware", "cookware",
        "kitchen equipment", "kitchen equipments", "cooking vessel", "vessel",
        "vessels", "steel utensils", "stainless steel utensils", "pot", "pots",
        "pan", "pans", "kadai", "kadhai", "tawa", "tava", "pressure cooker",
        "cooker", "cooking pot", "stock pot", "degchi", "patila", "thali",
        "plate", "plates", "bowl", "bowls", "glass steel", "spoon", "spoons",
        "serving spoon", "ladle", "cutlery", "commercial kitchen equipment",
        "canteen equipment", "mess utensils", "kitchen utensil", "cooking utensil",
        "steel plate", "steel thali", "steel glass", "steel bowl", "utensiles",
        "utencils", "bartaan", "kitchen tool", "food container", "casserole",
        "hot case", "hot pot", "chapati maker", "dosa tawa", "idli maker",
        "cooking range", "gas stove", "burner", "chafing dish",
    ]),
    "PPE / Medical Consumables": ("mask glove sanitizer ppe", [
        "mask", "masks", "face mask", "surgical mask", "n95 mask", "n95",
        "3 ply mask", "ffp2 mask", "kn95 mask", "gloves", "hand gloves",
        "surgical gloves", "latex gloves", "nitrile gloves", "examination gloves",
        "rubber gloves", "sanitizer", "sanitiser", "hand sanitizer", "hand wash",
        "handwash", "ppe kit", "ppe", "personal protective equipment", "face shield",
        "safety goggles", "head cap", "surgical cap", "shoe cover", "gown",
        "surgical gown", "isolation gown", "coverall ppe", "apron", "disposable apron",
        "syringe", "syringes", "needle", "cotton", "surgical cotton", "bandage",
        "gauze", "dressing material", "thermometer", "oximeter", "pulse oximeter",
        "medical consumable", "disposable mask", "protective mask", "sanitizer bottle",
        "alcohol sanitizer", "disinfectant", "medical gloves", "examination glove",
        "mastik", "maask", "hand glove",
    ]),
    "Cleaning / Housekeeping": ("cleaning housekeeping supplies", [
        "cleaning", "housekeeping", "safai", "safayi", "jhadu", "jhaadu",
        "broom", "brooms", "mop", "mops", "floor mop", "wiper", "floor wiper",
        "phenyl", "phenyle", "phenol", "disinfectant", "floor cleaner",
        "toilet cleaner", "glass cleaner", "detergent", "detergent powder",
        "washing powder", "soap", "hand soap", "liquid soap", "dish wash",
        "dishwash", "scrubber", "scrub pad", "duster", "cleaning cloth",
        "microfiber cloth", "garbage bag", "dustbin bag", "trash bag", "dustbin",
        "waste bin", "toilet brush", "cleaning brush", "bleaching powder",
        "acid cleaner", "housekeeping material", "cleaning material", "cleaning supplies",
        "sanitation material", "naphthalene balls", "room freshener", "air freshener",
        "cleaning chemical", "housekeeping chemical", "pochha", "pocha", "wiper blade",
        "hand towel", "tissue paper", "toilet roll", "cleaning equipment",
        "vacuum cleaner", "scrubbing machine",
    ]),
    "Books / Education Material": ("book education stationery learning", [
        "book", "books", "kitab", "kitaab", "text book", "textbook", "text books",
        "note book", "notebook", "exercise book", "reference book", "guide book",
        "library book", "school book", "college book", "academic book",
        "printed book", "story book", "dictionary", "encyclopedia", "atlas",
        "workbook", "practice book", "question bank", "study material",
        "educational material", "learning material", "teaching material",
        "chart", "charts", "educational chart", "wall chart", "map", "globe",
        "stationery book", "diary", "diaries", "planner", "register book",
        "log book", "attendance register", "kitaben", "buk", "bookss",
        "reading book", "publication", "journal", "magazine", "periodical",
        "manual book", "handbook", "syllabus book", "coaching book", "ncert book",
        "competitive book", "children book", "picture book", "activity book",
    ]),
    "Networking / Router / Switch": ("router switch network networking", [
        "router", "routers", "wifi router", "wireless router", "network router",
        "switch", "switches", "network switch", "ethernet switch", "poe switch",
        "managed switch", "unmanaged switch", "l2 switch", "l3 switch",
        "24 port switch", "48 port switch", "8 port switch", "modem", "adsl modem",
        "access point", "wifi access point", "wireless access point", "ap",
        "firewall", "network firewall", "gateway", "networking equipment",
        "networking device", "lan switch", "gigabit switch", "core switch",
        "distribution switch", "edge switch", "wifi device", "hotspot device",
        "range extender", "wifi extender", "repeater", "wifi repeater",
        "network router switch", "internet router", "broadband router", "rowter",
        "ruter", "netwrk switch", "networkswitch", "structured cabling",
        "patch panel", "patch cord", "rack switch", "poe injector", "sfp module",
        "network card", "nic",
    ]),
    "Storage / Hard Disk / Pen Drive": ("storage disk drive memory", [
        "hard disk", "harddisk", "hard drive", "hdd", "ssd", "solid state drive",
        "external hard disk", "external hdd", "internal hard disk", "portable hard disk",
        "pen drive", "pendrive", "usb drive", "flash drive", "thumb drive",
        "memory card", "sd card", "micro sd card", "micro sd", "storage device",
        "storage media", "1tb hard disk", "2tb hard disk", "500gb hard disk",
        "1 tb hdd", "2 tb hdd", "usb stick", "otg pen drive", "nvme ssd",
        "sata ssd", "m.2 ssd", "external ssd", "data storage", "backup drive",
        "storage drive", "disk drive", "hard disc", "harddrive", "pen driv",
        "pendriv", "usb pendrive", "16gb pen drive", "32gb pen drive",
        "64gb pen drive", "128gb pen drive", "nas storage", "san storage",
        "network storage", "memory stick", "storage disk", "cloud storage device",
        "backup hard disk", "external storage", "removable storage", "flash memory",
    ]),
    "Camera / Photography": ("camera photography digital lens", [
        "camera", "cameras", "digital camera", "dslr", "dslr camera", "mirrorless camera",
        "point and shoot camera", "compact camera", "action camera", "video camera",
        "camcorder", "webcam", "web camera", "web cam", "document camera",
        "photography camera", "professional camera", "slr camera", "camera lens",
        "lens", "zoom lens", "prime lens", "telephoto lens", "tripod", "camera tripod",
        "gimbal", "camera stand", "photography equipment", "still camera",
        "instant camera", "camra", "kemra", "kamera", "camera device",
        "handycam", "gopro", "sports camera", "360 camera", "camera kit",
        "camera body", "camera flash", "external flash", "memory card camera",
        "camera bag", "photography lens", "cctv is separate", "field camera",
        "surveillance is separate", "recording camera", "hd video camera",
        "4k camera", "broadcast camera", "studio camera", "photo camera",
        "imaging camera", "camera accessory",
    ]),
    "Sound System / PA / Microphone": ("microphone speaker sound audio pa", [
        "microphone", "microphones", "mic", "mics", "mike", "mikes", "wireless mic",
        "cordless mic", "collar mic", "lapel mic", "handheld mic", "gooseneck mic",
        "condenser mic", "dynamic mic", "speaker", "speakers", "loudspeaker",
        "pa system", "public address system", "public addressing system",
        "amplifier", "amplifiers", "audio amplifier", "mixer", "audio mixer",
        "sound mixer", "sound system", "audio system", "sound equipment",
        "column speaker", "wall speaker", "ceiling speaker", "horn speaker",
        "megaphone", "loud hailer", "portable speaker", "bluetooth speaker",
        "conference audio", "conference mic", "audio conferencing", "sound box",
        "spekar", "speeker", "maik", "mikrophone", "microfone", "audio speaker",
        "pa amplifier", "pa speaker", "auditorium sound system", "line array speaker",
        "subwoofer", "sub woofer", "sound reinforcement", "voice amplifier",
        "portable pa system", "trolley speaker",
    ]),
    "Generator / DG Set": ("generator diesel dg power", [
        "generator", "generators", "genset", "gen set", "dg set", "d.g. set",
        "diesel generator", "diesel genset", "silent generator", "portable generator",
        "petrol generator", "gas generator", "inverter generator", "power generator",
        "standby generator", "backup generator", "5 kva generator", "10 kva generator",
        "15 kva generator", "25 kva generator", "62.5 kva generator", "100 kva generator",
        "diesel engine generator", "electric generator", "generator set",
        "power generation set", "genrator", "genretor", "jenerator", "generater",
        "diesel dg set", "silent dg set", "canopy generator", "acoustic generator",
        "engine generator", "prime power generator", "emergency generator",
        "generator on rent", "generator hire", "captive power generator",
        "generating set", "kirloskar generator", "cummins generator", "mahindra genset",
        "sound proof generator", "trolley generator", "generator maintenance",
        "generator amc", "single phase generator", "three phase generator",
        "high capacity generator", "industrial generator",
    ]),
    "Cable / Wire": ("cable wire electrical conductor", [
        "cable", "cables", "wire", "wires", "taar", "tar", "electrical cable",
        "electric wire", "power cable", "copper cable", "aluminium cable",
        "armoured cable", "unarmoured cable", "xlpe cable", "pvc cable",
        "flexible cable", "control cable", "instrumentation cable", "ht cable",
        "lt cable", "house wire", "building wire", "single core cable",
        "multi core cable", "3 core cable", "4 core cable", "coaxial cable",
        "lan cable", "ethernet cable", "cat6 cable", "cat 6 cable", "network cable",
        "usb cable", "hdmi cable", "extension cable", "welding cable", "solar cable",
        "copper wire", "aluminium wire", "electrical wire", "wiring cable",
        "cabel", "kebal", "keble", "cabel wire", "wire cable", "conductor",
        "insulated wire", "earthing wire", "binding wire", "gi wire", "fencing wire",
        "power supply cable", "communication cable", "optical fibre cable",
        "fiber cable", "data cable",
    ]),
    "Bag / Backpack": ("bag backpack luggage carry", [
        "bag", "bags", "basta", "bastaa", "thaila", "thela", "backpack", "back pack",
        "school bag", "college bag", "laptop bag", "office bag", "travel bag",
        "duffle bag", "duffel bag", "trolley bag", "suitcase", "luggage",
        "hand bag", "handbag", "sling bag", "shoulder bag", "messenger bag",
        "rucksack", "haversack", "kit bag", "gunny bag", "jute bag", "cloth bag",
        "cotton bag", "non woven bag", "carry bag", "shopping bag", "conference bag",
        "document bag", "file bag", "tool bag", "army bag", "combat bag",
        "waterproof bag", "waist bag", "pouch", "bagpack", "bagpak", "beg",
        "baig", "pittu bag", "rack bag", "delegate bag", "promotional bag",
        "canvas bag", "leather bag", "polyester bag", "nylon bag", "utility bag",
        "field bag", "medical bag", "first aid bag",
    ]),
}


def build(path):
    rows = []
    for concept, (hint, terms) in CONCEPTS.items():
        seen, clean_terms = set(), []
        for t in terms:
            tl = " ".join(t.lower().strip().split())
            if tl and tl not in seen:
                seen.add(tl)
                clean_terms.append(tl)
        rows.append({
            "concept": concept,
            "category_hint": hint,
            "terms": ";".join(clean_terms),
        })
        print(f"{concept:42s} {len(clean_terms)} terms")

    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["concept", "category_hint", "terms"])
        w.writeheader()
        w.writerows(rows)
    print(f"\nWrote {len(rows)} concepts -> {path}")


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    # write into the project root
    target = os.environ.get("SYN_OUT", "synonyms.csv")
    build(target)
